id = "theme-yue"
name = "Yue"
version = "0.5.0"
schema_version = 1
authors = ["blaqat <blaqat.ag@gmail.com>"]
description = "Theme based off of the theme from the moonscript.org code examples"
repository = "https://github.com/blaqat/zed-themes/yue"
